### ISSUE TITLE
error wg

### ISSUE THREAD

**Issue by levarar** [jacky8399/FakeSnow#1]
[02:13:10 ERROR]: Could not pass event WorldLoadEvent to FakeSnow v1.0
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at com.sk89q.worldguard.WorldGuard.getPlatform(WorldGuard.java:100) ~[?:?]
        at com.jacky8399.fakesnow.Events.onWorldLoad(Events.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor23.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:452) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:240) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[02:13:10 ERROR]: Could not pass event WorldLoadEvent to FakeSnow v1.0
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at com.sk89q.worldguard.WorldGuard.getPlatform(WorldGuard.java:100) ~[?:?]
        at com.jacky8399.fakesnow.Events.onWorldLoad(Events.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor23.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:452) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:240) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[02:13:10 ERROR]: Could not pass event WorldLoadEvent to FakeSnow v1.0
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at com.sk89q.worldguard.WorldGuard.getPlatform(WorldGuard.java:100) ~[?:?]
        at com.jacky8399.fakesnow.Events.onWorldLoad(Events.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor23.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:452) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:240) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Tuinity-"0850468"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by Hellohi3654** [comment]
Have you got world guard?

**Comment by jacky8399** [comment]
Update 1.1 should fix the spam in the console. Could you try it out? Thanks
