### ISSUE TITLE
Plugin does not work in spigot server

### ISSUE THREAD

**Issue by JaBaZebs** [jacky8399/FakeSnow#4]
Exception:
[ERROR] [FakeSnow] Unhandled exception number 128 occurred in onPacketSending(PacketEvent) for FakeSnow

java.lang.NoSuchFieldError: locX

at com.jacky8399.fakesnow.PacketListener.copyBiomes(PacketListener.java:57) ~[?:?]

at com.jacky8399.fakesnow.PacketListener.updatePacketNew(PacketListener.java:264) ~[?:?]

at com.jacky8399.fakesnow.PacketListener.onPacketSending(PacketListener.java:359) ~[?:?]

at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]

at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[?:?]

at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[?:?]

at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[?:?]

at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[?:?]

at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]

at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]

at net.minecraft.network.NetworkManager.b(NetworkManager.java:212) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.network.NetworkManager.a(NetworkManager.java:192) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1836) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1822) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1968) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:1413) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.level.PlayerChunkMap.lambda$53(PlayerChunkMap.java:840) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]

at net.minecraft.server.level.PlayerChunkMap.lambda$52(PlayerChunkMap.java:839) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[datafixerupper-5.0.28.jar:?]

at net.minecraft.server.level.PlayerChunkMap.lambda$50(PlayerChunkMap.java:835) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]

at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]

at net.minecraft.server.level.ChunkTaskQueueSorter.b(SourceFile:62) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.level.ChunkProviderServer$b.d(ChunkProviderServer.java:633) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.level.ChunkProviderServer$b.x(ChunkProviderServer.java:644) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.level.ChunkProviderServer.d(ChunkProviderServer.java:315) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1138) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:116) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1105) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at java.lang.Thread.run(Thread.java:833) [?:?]

[ERROR] [FakeSnow] Unhandled exception number 256 occurred in onPacketSending(PacketEvent) for FakeSnow

java.lang.NoSuchFieldError: locX

at com.jacky8399.fakesnow.PacketListener.copyBiomes(PacketListener.java:57) ~[?:?]

at com.jacky8399.fakesnow.PacketListener.updatePacketNew(PacketListener.java:264) ~[?:?]

at com.jacky8399.fakesnow.PacketListener.onPacketSending(PacketListener.java:359) ~[?:?]

at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]

at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[?:?]

at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[?:?]

at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[?:?]

at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[?:?]

at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]

at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]

at net.minecraft.network.NetworkManager.b(NetworkManager.java:212) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.network.NetworkManager.a(NetworkManager.java:192) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1836) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1822) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1968) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:1413) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.level.PlayerChunkMap.lambda$53(PlayerChunkMap.java:840) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]

at net.minecraft.server.level.PlayerChunkMap.lambda$52(PlayerChunkMap.java:839) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[datafixerupper-5.0.28.jar:?]

at net.minecraft.server.level.PlayerChunkMap.lambda$50(PlayerChunkMap.java:835) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]

at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]

at net.minecraft.server.level.ChunkTaskQueueSorter.b(SourceFile:62) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.level.ChunkProviderServer$b.d(ChunkProviderServer.java:633) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.level.ChunkProviderServer$b.x(ChunkProviderServer.java:644) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.level.ChunkProviderServer.d(ChunkProviderServer.java:315) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1138) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:116) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1105) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]

at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by jacky8399** [comment]
Thanks for the bug report! This has been fixed in 1.3.1.1.
