### ISSUE TITLE
1.20.6 support

### ISSUE THREAD

**Issue by mimimiartartart** [jacky8399/FakeSnow#7]
Hello! Are you planning to make a plugin for version 1.20.6?

**Comment by jacky8399** [comment]
This jar is built against 1.20.5/6, but I don't have a 1.20.6 testing environment so it's untested.
[FakeSnow-1.3.3-1.20.6fork.jar.zip](https://github.com/user-attachments/files/18298253/FakeSnow-1.3.3-1.20.6fork.jar.zip)

**Comment by mimimiartartart** [comment]
Dont work :(
`[01:16:48] [Server thread/ERROR]: Could not load 'plugins\FakeSnow-1.3.3-1.20.6fork.jar'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.21
        at org.bukkit.craftbukkit.v1_20_R4.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:303) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4195-b-Spigot-f6a4805-6524758]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:313) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:122) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.loadPlugins(CraftServer.java:453) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4195-b-Spigot-f6a4805-6524758]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:232) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4195-b-Spigot-f6a4805-6524758]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4195-b-Spigot-f6a4805-6524758]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4195-b-Spigot-f6a4805-6524758]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]`

**Comment by jacky8399** [comment]
[FakeSnow-1.3.3-1.20.6fork.jar.zip](https://github.com/user-attachments/files/18418030/FakeSnow-1.3.3-1.20.6fork.jar.zip)

**Comment by mimimiartartart** [comment]
It's working, thanks
